# Configuración de Servidor (Dinámico para Cloud Run)
server.port=${PORT:8080}

# Configuración de Base de Datos (PostgreSQL / Supabase Ready)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crm_enterprise}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Research21@}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config (Secret Key parametrizado)
jwt.secret=${JWT_SECRET:7d8a946b219f7fc98b15e45a50785f81bf83579ea0dbd8ae311cc28fbf656b82}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Mail Config (Ocultando credenciales sensibles)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:rodrigodaremberg@gmail.com}
spring.mail.password=${MAIL_PASSWORD:arytcsguyirnqjor}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
